### ISSUE TITLE
Regarding strange behavior for the scalar field.

### ISSUE THREAD

**Issue by abhijit-c** [NYUGeometricModeling/GM_Assignment_4#3]
Hi:

I was writing up the report of my assignment, and I noticed a spot of strange behavior on my Scalar Field. It seems that the point at which the vertex value was fixed to zero (due to the system not having full rank) has strange behavior. Any recommendations on how to fix this in the general case? The way I interpolated the scalar field with the extra constraint was by reducing the energy given into a Matrix system and then adding in Lagrangian constraints. Maybe I would be better off using soft constraints?

![prescal](https://user-images.githubusercontent.com/14017302/38541831-3f095abe-3c6e-11e8-91ed-8d4fcc758119.png)
![scal](https://user-images.githubusercontent.com/14017302/38541830-3efee0d4-3c6e-11e8-8f9f-03baf7f6cd8c.png)

**Comment by jiangzhongshi** [comment]
Hi,

In general, you are solving a min E(u) s.t. constraints(u) problem, 
if you are fixing u_0 = 0 it will simply make another constraint in the solver, where I think you should still be able to construct a solvable system, as long as the constraints of u don't conflict.

Best,
Zhongshi

**Comment by abhijit-c** [comment]
Right it ends up being another row and column on the right hand side of my system with ones at the very bottom right and top ri

**Comment by abhijit-c** [comment]
I see, so the strange region of my scalar field is possibly being produced due to conflicts in my in my given constraint? I will experiment with that and see how it goes.

**Comment by jiangzhongshi** [comment]
That's one possibility. It seems to me in this image you are constraining the coordinate of the leftmost triangle to be 1?

Alternatively, please try to print out the constraints after solve and check if they are what you wanted. And also plot the reconstruction error to get a better idea.

**Comment by abhijit-c** [comment]
Yes, I figured out there was a strange error with the input of the constrained error that I missed. Working now, thanks!
