### ISSUE TITLE
Which basis to choose

### ISSUE THREAD

**Issue by smoothclear** [NYUGeometricModeling/GM_Assignment_4#4]
Hi,

Could I ask a question about the local orthogonal reference system for each triangle? I noticed that in the main.cpp, "igl::local_basis" is used to compute the basis for each triangle mesh. In the tutorial_nrosy.cpp, the local system is computed directly from the edge of the mesh. So a little bit confused which method we should use or both are OK?

Thanks a lot.

**Comment by jiangzhongshi** [comment]
Hi,

As long as there's a basis, it's fine. So both method would work and I think they should have implemented the same thing.

**Comment by smoothclear** [comment]
Got that.
Thanks.
